# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null

jobs:
    - template: sign-release-package.yaml
      parameters:
          unsignedPipelineResource: ${{ parameters.unsignedPipelineResource }}
          unsignedArtifactName: ${{ parameters.unsignedArtifactName }}
          signedArtifactName: ${{ parameters.signedArtifactName }}
          vmImage: macOS-10.15
          filePattern: '*.dmg, *.zip'
          platform: mac
          inlineSignParams: |
              [
                  {
                      "keyCode": "CP-401337-Apple",
                      "operationSetCode": "MacAppDeveloperSign",
                      "parameters": [],
                      "toolName": "sign",
                      "toolVersion": "1.0"
                  }
              ]
